version: '3'

services:
        spring-app:
                depends_on:
                        - eureka-server
                container_name: spring-app
                build:
                        context: ./docker
                        dockerfile: spring.dockerfile
                volumes:
                        - ./app:/app
                environment:
                        APP_NAME: test-app-1
                command: sh -c "/usr/bin/java -jar /app/target/yet-another-lab-lab.jar"

        eureka-server:
                depends_on:
                        - db
                container_name: eureka-server
                build:
                        context: ./docker
                        dockerfile: spring.dockerfile
                volumes:
                        - ./eureka-server:/app
                ports:
                  - "8761:8761"
                command: sh -c "/usr/bin/java -jar /app/target/eureka-server-lab.jar"
        eureka-client:
                depends_on:
                        - config-server
                        - rabbit-mq
                        - eureka-server
                        - rabbit-mq-consumer
                container_name: eureka-client
                build:
                        context: docker
                        dockerfile: spring.dockerfile
                volumes:
                        - ./eureka-client:/app
                command: sh -c "/cmd/awaiter.sh && /usr/bin/java -jar /app/target/eureka-client-lab.jar"

        config-server:
                depends_on:
                  - rabbit-mq
                build:
                  context: docker
                  dockerfile: spring.dockerfile
                container_name: config-server
                volumes:
                        - ./config-server:/app
                ports:
                  - "9999:8888"
                command: sh -c "/usr/bin/java -jar /app/target/config-server-lab.jar"
        rabbit-mq:
                image: rabbitmq:3.8.0-beta.3-management
                hostname: rabbit-mq
                container_name: rabbit-mq
                environment:
                        RABBITMQ_ERLANG_COOKIE: secret
                        RABBITMQ_NODENAME: rabbit@rabbit-mq
                ports:
                        - "15672:15672"
        rabbit-mq-consumer:
                depends_on:
                  - rabbit-mq
                build:
                        context: ./docker
                        dockerfile: spring.dockerfile
                container_name: rabbit-mq-consumer
                volumes:
                        - ./queue-consumer:/app
                command: sh -c "sleep 10 && /usr/bin/java -jar /app/target/hosting-queue-consumer-lab.jar"

        proxy:
                container_name: proxy
                image: nginx:alpine
                volumes:
                  - ./frontend/nginx:/etc/nginx
                depends_on:
                  - eureka-client
                  - frontend
                ports:
                  - "80:80"
        frontend:
                container_name: frontend
                image: node:12.4-alpine
                working_dir: /www/data/vue
                command: npm run serve
                volumes:
                        - ./frontend/vue:/www/data/vue

        db:
                container_name: spring-db
                image: mysql:5.7
                volumes:
                        - db_data:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: secret
                        MYSQL_DATABASE: springdb
                ports:
                        - "33061:3306"
volumes:
        db_data:
        maven_cache: