version: '3'

services:
        spring-app:
                depends_on:
                        - eureka-server
                container_name: spring-app
                build:
                        context: ./app
                        dockerfile: docker/spring.docker
                volumes:
                        - ./app:/usr/src/app
                        - maven_cache:/usr/src/.maven-cache
                networks:
                        - default
                environment:
                        DB_HOST: spring-db:3306
                        APP_NAME: test-app-1
        spring-app-2:
                depends_on:
                        - eureka-server
                container_name: spring-app-2
                build:
                        context: ./app
                        dockerfile: docker/spring.docker
                volumes:
                        - ./app:/usr/src/app
                        - maven_cache:/usr/src/.maven-cache
                networks:
                        - default
                environment:
                        DB_HOST: spring-db:3306
                        APP_NAME: not-test-app-2
        eureka-server:
                depends_on:
                        - db
                container_name: eureka-server
                build:
                        context: ./eureka-server
                        dockerfile: docker/spring.docker
                volumes:
                        - ./eureka-server:/usr/src/eureka-server
                        - maven_cache:/usr/src/.maven-cache
                networks:
                        - default
                ports:
                  - "8761:8761"
                environment:
                        DB_HOST: spring-db:3306
        eureka-client:
                depends_on:
                        - config-server
                container_name: eureka-client
                build:
                        context: ./eureka-client
                        dockerfile: docker/spring.docker
                volumes:
                        - ./eureka-client:/usr/src/eureka-client
                        - maven_cache:/usr/src/.maven-cache
                ports:
                        - "8080:80"
                networks:
                        - default
                environment:
                        DB_HOST: spring-db:3306
        config-server:
                depends_on:
                  - eureka-server
                build:
                  context: ./config-server
                  dockerfile: docker/spring.docker
                container_name: config-server
                volumes:
                        - ./config-server:/usr/src/config-server
                        - maven_cache:/usr/src/.maven-cache
                ports:
                        - "8888:8888"
                networks:
                        - default
                environment:
                        DB_HOST: spring-db:3306
        rabbit-mq:
                image: rabbitmq:3.8-rc
                hostname: rabbit-mq
                networks:
                  - default
                environment:
                        RABBITMQ_ERLANG_COOKIE: secret
                        RABBITMQ_NODENAME: rabbit@rabbit-mq
        db:
                container_name: spring-db
                build:
                        context: ./docker
                        dockerfile: database.docker
                volumes:
                        - db_data:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: secret
                        MYSQL_DATABASE: springdb
                ports:
                        - "33061:3306"
volumes:
        db_data:
        maven_cache: